Hw04 lru cache
fi1atov/go_otus_hw_professional pull request #4
Opened 2024-05-11 19:04 UTC by fi1atov

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-05-12 05:11 UTC, vladislavmass requested changes

2024-05-12 05:11 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	c.items = map[Key]*ListItem{}
Тут все таки лучше использовать make  и сразу задать размер мамы, раз мы его знаем

2024-05-12 05:11 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	c.items = map[Key]*ListItem{}
Очередь тоже нужно пересоздать

2024-05-12 05:11 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.first != nil { // (это условно)
Подскажите пожалуйста случай, когда `l.last==nil,` а `l.first!=nil`

2024-05-12 05:11 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.first != nil {
`l.first == nil` может произойти всего в одном случае, когда мы переносим единственный элемент вперед. Но зачем? Зачем нам вообще куда либо переносить элемент который был 1?

2024-05-12 11:44 UTC, fi1atov commented on hw04_lru_cache/list.go
> +	if l.first != nil { // (это условно)
l.first!=nil - это когда наш список пустой, т.е. в нем нет элементов, и вставляемый элемент является первым.
Если ранее не было элементов, соответственно не надо у них пытаться искать Prev

2024-05-12 11:51 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.first != nil { // (это условно)
Мне скорее интересна ситуация когда одновременно `l.last==nil` и `l.first!=nil`. И получается что это не отдельный if а else к предыдущему условию

2024-05-12 11:54 UTC, fi1atov commented on hw04_lru_cache/list.go
> +	if l.first != nil {
Да, согласен. Условие лишнее - этот кусок кода скопировал из PushFront и не подумал. Убрал

2024-05-12 11:57 UTC, fi1atov commented on hw04_lru_cache/list.go
> +	if l.first != nil { // (это условно)
Кажется, это невозможное условие чтобы и l.last==nil и l.first!=nil

2024-05-12 14:49 UTC, fi1atov commented on hw04_lru_cache/list.go
> +	if l.first != nil { // (это условно)
Объединил в один if-else

2024-05-12 14:52 UTC, fi1atov commented on hw04_lru_cache/cache.go
> +	c.items = map[Key]*ListItem{}
Сделал. Добавил цикл который идет по всем элементам и удаляет их

2024-05-12 14:52 UTC, fi1atov commented on hw04_lru_cache/cache.go
> +	c.items = map[Key]*ListItem{}
Добавил

2024-05-13 10:06 UTC, vladislavmass approved these changes

2024-05-13 10:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.first == nil { // (это условно)
Опять if вместо else

2024-05-13 10:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	l.Remove(i)
Тут хотелось бы видеть выход сразу, если элемент и так первый

2024-05-13 12:25 UTC, merged